version: '3.8'

services:
  rocketchat:
    image: ghcr.io/rocketchat/rocket.chat:6.7.3-htchat-r1
    container_name: rocketchat
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - ROOT_URL=https://im.lc2023.com
      - PORT=3000
      - DEPLOY_METHOD=docker
      - NODE_ENV=production
      - MAIL_URL=smtp://your-smtp-server:587
      - MAIL_FROM=noreply@lc2023.com
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=ChangeThisPassword123!
      - ADMIN_EMAIL=admin@lc2023.com
      - OVERWRITE_SETTING_Show_Setup_Wizard=completed
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - rocketchat_uploads:/app/uploads
      - rocketchat_data:/app/data
    networks:
      - rocketchat_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rocketchat
      - MONGO_INITDB_ROOT_PASSWORD=ChangeThisMongoPassword123!
      - MONGO_INITDB_DATABASE=rocketchat
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rocketchat_network
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine wiredTiger
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mongo-init-replica:
    image: mongo:6.0
    container_name: mongo-init-replica
    restart: "no"
    depends_on:
      - mongo
    networks:
      - rocketchat_network
    command: >
      mongosh --host mongo:27017 --eval '
        var config = {
          "_id": "rs0",
          "version": 1,
          "members": [
            {
              "_id": 1,
              "host": "mongo:27017",
              "priority": 1
            }
          ]
        };
        rs.initiate(config, { force: true });
      '

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - rocketchat
    networks:
      - rocketchat_network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: "no"
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@lc2023.com --agree-tos --no-eff-email -d im.lc2023.com

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local
  rocketchat_uploads:
    driver: local
  rocketchat_data:
    driver: local

networks:
  rocketchat_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16